# Generated by Django 3.1.7 on 2021-02-25 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstdbtest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_dob',
            field=models.DateTimeField(verbose_name='%d-%m-%Y'),
        ),
    ]
